/**
 * G-VISTA High-Fidelity Mock Dataset
 * Statewide Gujarat video intelligence data aligned with backend schemas.
 */

export const MOCK_CAMERAS = [
  {
    id: 1,
    camera_uid: 'CAM-AHM-001',
    name: 'Sabarmati Riverfront North Promenade',
    department: 'Police',
    district: 'Ahmedabad',
    location: 'Riverfront Central Walkway, Gate 2',
    type: 'PTZ Dome',
    latitude: 23.0415,
    longitude: 72.5789,
    vms_vendor: 'Axis Communications Q6075-E',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '12 Jan 2025',
    power_source: 'PoE+ (IEEE 802.3at)',
    warranty_status: 'Active (Until Oct 2027)',
    ai_enabled: true,
    fps: 30,
    resolution: '4K (3840x2160)',
    created_at: '2026-08-10T09:00:00Z',
    updated_at: '2026-09-13T10:00:00Z',
    maintenance: {
      last_serviced: '14 Aug 2026',
      next_scheduled: '14 Nov 2026',
      contractor: 'Gujarat Infotech Ltd',
      firmware: 'v4.12.8-p3',
      uptime_pct: '99.8%',
    },
    history: [
      { date: '2026-09-12 14:32', event: 'Protocol handshake verified (RTSP 200 OK)', author: 'System' },
      { date: '2026-08-14 11:15', event: 'Quarterly lens clean & wiper seal check completed', author: 'Tech #42' },
      { date: '2026-06-20 09:30', event: 'Security firmware upgrade v4.12.8 applied', author: 'VMS Admin' },
      { date: '2025-01-12 10:00', event: 'Commissioning & GIS geo-tagging complete', author: 'Installer Team' },
    ],
  },
  {
    id: 2,
    camera_uid: 'CAM-AHM-002',
    name: 'Kalupur Central Railway Station Gate 1',
    department: 'Transport',
    district: 'Ahmedabad',
    location: 'Kalupur Transit Hub Main Portico',
    type: 'ANPR High-Speed',
    latitude: 23.0305,
    longitude: 72.6008,
    vms_vendor: 'CP Plus Intellinet 8MP',
    protocol_type: 'ONVIF',
    status: 'Online',
    installed_on: '15 Jan 2025',
    power_source: 'AC Mains 230V + UPS Hybrid',
    warranty_status: 'Active (Until Jan 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-10T09:15:00Z',
    updated_at: '2026-09-13T10:30:00Z',
    maintenance: {
      last_serviced: '10 Aug 2026',
      next_scheduled: '10 Nov 2026',
      contractor: 'Western Rail Telematics',
      firmware: 'v2.8.4',
      uptime_pct: '99.5%',
    },
    history: [
      { date: '2026-09-11 08:20', event: 'ANPR plate optical recalibration passed', author: 'AI Engine' },
      { date: '2026-08-10 16:00', event: 'UPS battery impedance test normal', author: 'Tech #18' },
      { date: '2025-01-15 11:30', event: 'Integration into Gujarat Transport GIS', author: 'Installer Team' },
    ],
  },
  {
    id: 3,
    camera_uid: 'CAM-AHM-003',
    name: 'Ahmedabad Civil Hospital Trauma Center Entrance',
    department: 'Health',
    district: 'Ahmedabad',
    location: 'Asarwa Health Complex Ward B',
    type: 'Bullet Fixed',
    latitude: 23.0526,
    longitude: 72.6033,
    vms_vendor: 'Hikvision DarkFighter',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '02 Feb 2025',
    power_source: 'Hospital Emergency Grid + PoE',
    warranty_status: 'Active (Until Feb 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '4K (3840x2160)',
    created_at: '2026-08-11T09:00:00Z',
    updated_at: '2026-09-13T11:00:00Z',
    maintenance: {
      last_serviced: '02 Aug 2026',
      next_scheduled: '02 Nov 2026',
      contractor: 'Gujarat Medical Infra Corp',
      firmware: 'v5.7.1',
      uptime_pct: '99.9%',
    },
    history: [
      { date: '2026-09-10 12:00', event: 'Night IR illumination sensor nominal', author: 'System' },
      { date: '2026-08-02 10:45', event: 'Sterile area enclosure seal certified', author: 'Tech #09' },
    ],
  },
  {
    id: 4,
    camera_uid: 'CAM-AHM-004',
    name: 'Gujarat University Academic Block North',
    department: 'Education',
    district: 'Ahmedabad',
    location: 'Navrangpura University Enclave',
    type: 'Fisheye 360°',
    latitude: 23.0372,
    longitude: 72.5463,
    vms_vendor: 'Hanwha Techwin Wisenet',
    protocol_type: 'ONVIF',
    status: 'Online',
    installed_on: '18 Feb 2025',
    power_source: 'Campus Solar Solar Hybrid',
    warranty_status: 'Active (Until Feb 2027)',
    ai_enabled: true,
    fps: 25,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-11T10:00:00Z',
    updated_at: '2026-09-13T11:30:00Z',
    maintenance: {
      last_serviced: '20 Jul 2026',
      next_scheduled: '20 Oct 2026',
      contractor: 'Higher Edu Smart Campus Net',
      firmware: 'v3.1.2',
      uptime_pct: '99.2%',
    },
    history: [
      { date: '2026-09-08 17:00', event: 'Panoramic de-warping pipeline updated', author: 'System' },
      { date: '2026-07-20 14:10', event: 'Campus Wi-Fi 6 mesh backbone synced', author: 'Tech #31' },
    ],
  },
  {
    id: 5,
    camera_uid: 'CAM-AHM-005',
    name: 'Manek Chowk Heritage Market Perimeter',
    department: 'Municipal Corporation',
    district: 'Ahmedabad',
    location: 'Old Walled City Food Street',
    type: 'PTZ Dome',
    latitude: 23.0248,
    longitude: 72.5872,
    vms_vendor: 'Axis Communications Q6075-E',
    protocol_type: 'RTSP',
    status: 'Maintenance',
    installed_on: '05 Mar 2025',
    power_source: 'Municipal Street Lighting Grid',
    warranty_status: 'Active (Until Mar 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '4K (3840x2160)',
    created_at: '2026-08-12T08:00:00Z',
    updated_at: '2026-09-13T09:00:00Z',
    maintenance: {
      last_serviced: '13 Sep 2026',
      next_scheduled: '16 Sep 2026',
      contractor: 'AMC Smart City SPV',
      firmware: 'v4.10.2 (Pending Patch)',
      uptime_pct: '94.8%',
    },
    history: [
      { date: '2026-09-13 08:30', event: 'Scheduled optical motor realignment initiated', author: 'Tech #14' },
      { date: '2026-09-12 22:15', event: 'Azimuth mechanical drift reported by operator', author: 'Command Center' },
    ],
  },
  {
    id: 6,
    camera_uid: 'CAM-SRT-001',
    name: 'Surat Ring Road Majura Gate Flyover',
    department: 'Transport',
    district: 'Surat',
    location: 'Majura Gate Junction Overpass',
    type: 'ANPR High-Speed',
    latitude: 21.1824,
    longitude: 72.8198,
    vms_vendor: 'Hikvision DarkFighter 4K',
    protocol_type: 'RTSP',
    status: 'Active',
    installed_on: '12 Mar 2025',
    power_source: 'PoE+ (IEEE 802.3at)',
    warranty_status: 'Active (Until Mar 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '4K (3840x2160)',
    created_at: '2026-08-12T11:00:00Z',
    updated_at: '2026-09-13T11:20:00Z',
    maintenance: {
      last_serviced: '15 Aug 2026',
      next_scheduled: '15 Nov 2026',
      contractor: 'Surat Traffic Automated Sys',
      firmware: 'v5.9.0',
      uptime_pct: '99.7%',
    },
    history: [
      { date: '2026-09-13 11:20', event: 'Watchlist plate correlation trigger nominal', author: 'Pipeline 4' },
      { date: '2026-08-15 13:00', event: 'Highway speed radar sensor sync verified', author: 'Tech #22' },
    ],
  },
  {
    id: 7,
    camera_uid: 'CAM-SRT-002',
    name: 'Varachha Diamond Market Square',
    department: 'Police',
    district: 'Surat',
    location: 'Varachha Commercial High-Security Zone',
    type: 'PTZ Dome',
    latitude: 21.2144,
    longitude: 72.8592,
    vms_vendor: 'Dahua Ultra AI WizMind',
    protocol_type: 'HLS',
    status: 'Online',
    installed_on: '14 Mar 2025',
    power_source: 'Dual Line Commercial + Battery Bank',
    warranty_status: 'Active (Until Mar 2027)',
    ai_enabled: true,
    fps: 25,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-14T08:00:00Z',
    updated_at: '2026-09-13T12:00:00Z',
    maintenance: {
      last_serviced: '18 Aug 2026',
      next_scheduled: '18 Nov 2026',
      contractor: 'Gujarat Diamond Security Consortium',
      firmware: 'v3.8.1',
      uptime_pct: '99.9%',
    },
    history: [
      { date: '2026-09-12 10:00', event: 'Crowd density threshold checked (45 pers/m²)', author: 'Pipeline 3' },
      { date: '2026-08-18 15:45', event: 'Optical housing seal replaced', author: 'Tech #05' },
    ],
  },
  {
    id: 8,
    camera_uid: 'CAM-SRT-003',
    name: 'Surat New Civil Hospital Emergency Bay',
    department: 'Health',
    district: 'Surat',
    location: 'Majura Gate Medical Campus',
    type: 'Bullet Fixed',
    latitude: 21.1764,
    longitude: 72.8122,
    vms_vendor: 'Hanwha Techwin Wisenet',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '22 Mar 2025',
    power_source: 'Hospital Priority Circuit',
    warranty_status: 'Active (Until Mar 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-14T09:00:00Z',
    updated_at: '2026-09-13T10:00:00Z',
    maintenance: {
      last_serviced: '25 Aug 2026',
      next_scheduled: '25 Nov 2026',
      contractor: 'Health Infra Gujarat',
      firmware: 'v2.6.4',
      uptime_pct: '99.8%',
    },
    history: [
      { date: '2026-09-10 14:00', event: 'Ambulance bay perimeter clearance check passed', author: 'System' },
    ],
  },
  {
    id: 9,
    camera_uid: 'CAM-SRT-004',
    name: 'SVNIT Campus Main Gate Surveillance',
    department: 'Education',
    district: 'Surat',
    location: 'Ichchanath Institutional Corridor',
    type: 'Box Thermal',
    latitude: 21.1662,
    longitude: 72.7844,
    vms_vendor: 'Axis Communications Q1942-E',
    protocol_type: 'ONVIF',
    status: 'Online',
    installed_on: '28 Mar 2025',
    power_source: 'PoE+ (IEEE 802.3at)',
    warranty_status: 'Active (Until Mar 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-14T10:00:00Z',
    updated_at: '2026-09-13T10:30:00Z',
    maintenance: {
      last_serviced: '28 Aug 2026',
      next_scheduled: '28 Nov 2026',
      contractor: 'NIT Surveillance Network',
      firmware: 'v4.12.0',
      uptime_pct: '99.4%',
    },
    history: [
      { date: '2026-09-11 11:30', event: 'Thermal calibration sensor re-zeroed', author: 'Tech #17' },
    ],
  },
  {
    id: 10,
    camera_uid: 'CAM-SRT-005',
    name: 'Dumas Beach Public Promenade',
    department: 'Municipal Corporation',
    district: 'Surat',
    location: 'SMC Coastal Recreation Strip',
    type: 'PTZ Dome',
    latitude: 21.0833,
    longitude: 72.7167,
    vms_vendor: 'Hikvision DarkFighter',
    protocol_type: 'RTSP',
    status: 'Degraded',
    installed_on: '04 Apr 2025',
    power_source: 'Coastal Solar + Battery Backup',
    warranty_status: 'Active (Until Apr 2027)',
    ai_enabled: true,
    fps: 18,
    resolution: '720p (1280x720)',
    created_at: '2026-08-14T11:00:00Z',
    updated_at: '2026-09-13T09:00:00Z',
    maintenance: {
      last_serviced: '04 Aug 2026',
      next_scheduled: '18 Sep 2026',
      contractor: 'SMC Coastal Projects',
      firmware: 'v4.8.2',
      uptime_pct: '93.1%',
    },
    history: [
      { date: '2026-09-13 09:00', event: 'Salt spray mist fogging detected on optical glass', author: 'Pipeline 2' },
      { date: '2026-08-04 12:00', event: 'Corrosion inhibitor sprayed on aluminum base', author: 'Tech #28' },
    ],
  },
  {
    id: 11,
    camera_uid: 'CAM-VDR-001',
    name: 'Sayaji Baug Palace Perimeter West',
    department: 'Municipal Corporation',
    district: 'Vadodara',
    location: 'Sayaji Park West Gate Garden',
    type: 'Bullet Fixed',
    latitude: 22.3117,
    longitude: 73.1895,
    vms_vendor: 'Axis Communications M1137',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '15 Apr 2025',
    power_source: 'VMC Park Lighting Grid',
    warranty_status: 'Active (Until Apr 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-15T09:30:00Z',
    updated_at: '2026-09-13T09:45:00Z',
    maintenance: {
      last_serviced: '15 Aug 2026',
      next_scheduled: '15 Nov 2026',
      contractor: 'Vadodara Smart City SPV',
      firmware: 'v4.11.2',
      uptime_pct: '99.6%',
    },
    history: [
      { date: '2026-09-13 09:45', event: 'Perimeter tripwire detection nominal', author: 'Pipeline 3' },
    ],
  },
  {
    id: 12,
    camera_uid: 'CAM-VDR-002',
    name: 'Alkapuri Underpass Traffic Flow',
    department: 'Transport',
    district: 'Vadodara',
    location: 'Alkapuri West Commercial Crossing',
    type: 'ANPR High-Speed',
    latitude: 22.3106,
    longitude: 73.1705,
    vms_vendor: 'Hanwha Techwin Wisenet 4K',
    protocol_type: 'ONVIF',
    status: 'Online',
    installed_on: '18 Apr 2025',
    power_source: 'PoE+ (IEEE 802.3at)',
    warranty_status: 'Active (Until Apr 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-09-13T10:10:00Z',
    maintenance: {
      last_serviced: '20 Aug 2026',
      next_scheduled: '20 Nov 2026',
      contractor: 'VMC Transport Cell',
      firmware: 'v3.0.4',
      uptime_pct: '99.8%',
    },
    history: [
      { date: '2026-09-12 16:30', event: 'Underpass lighting compensation validated', author: 'System' },
    ],
  },
  {
    id: 13,
    camera_uid: 'CAM-VDR-003',
    name: 'SSG Government Hospital Emergency Ward',
    department: 'Health',
    district: 'Vadodara',
    location: 'Karelibaugh Medical Campus',
    type: 'Fisheye 360°',
    latitude: 22.3089,
    longitude: 73.1956,
    vms_vendor: 'CP Plus Intellinet',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '25 Apr 2025',
    power_source: 'Hospital Emergency Grid',
    warranty_status: 'Active (Until Apr 2028)',
    ai_enabled: true,
    fps: 25,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-15T11:00:00Z',
    updated_at: '2026-09-13T10:45:00Z',
    maintenance: {
      last_serviced: '25 Aug 2026',
      next_scheduled: '25 Nov 2026',
      contractor: 'Health Services Gujarat',
      firmware: 'v2.4.1',
      uptime_pct: '99.9%',
    },
    history: [
      { date: '2026-09-10 18:20', event: 'Triage waiting area congestion alert clear', author: 'Pipeline 3' },
    ],
  },
  {
    id: 14,
    camera_uid: 'CAM-VDR-004',
    name: 'MS University Faculty of Technology Gate',
    department: 'Education',
    district: 'Vadodara',
    location: 'Kala Bhavan Heritage Campus',
    type: 'Bullet Fixed',
    latitude: 22.3012,
    longitude: 73.1812,
    vms_vendor: 'Dahua WizMind',
    protocol_type: 'ONVIF',
    status: 'Offline',
    installed_on: '02 May 2025',
    power_source: 'Campus Sub-station Feed',
    warranty_status: 'Active (Until May 2027)',
    ai_enabled: true,
    fps: 0,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-15T12:00:00Z',
    updated_at: '2026-09-13T07:15:00Z',
    maintenance: {
      last_serviced: '02 Aug 2026',
      next_scheduled: '14 Sep 2026 (Urgent Ticket)',
      contractor: 'MSU Telecommunications',
      firmware: 'v3.2.0',
      uptime_pct: '92.4%',
    },
    history: [
      { date: '2026-09-13 07:15', event: 'Loss of link carrier detected by switch', author: 'Pipeline 2' },
      { date: '2026-09-13 07:30', event: 'Automated field ticket dispatched to MSU Techs', author: 'Operations Engine' },
    ],
  },
  {
    id: 15,
    camera_uid: 'CAM-GNR-001',
    name: 'Infocity Circle Surveillance Post',
    department: 'Police',
    district: 'Gandhinagar',
    location: 'Infocity IT Hub Circle NH-147',
    type: 'PTZ Dome',
    latitude: 23.1923,
    longitude: 72.6288,
    vms_vendor: 'Hikvision DarkFighter 4K',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '10 May 2025',
    power_source: 'PoE+ (IEEE 802.3at)',
    warranty_status: 'Active (Until May 2028)',
    ai_enabled: true,
    fps: 60,
    resolution: '4K (3840x2160)',
    created_at: '2026-08-17T07:45:00Z',
    updated_at: '2026-09-13T12:15:00Z',
    maintenance: {
      last_serviced: '10 Aug 2026',
      next_scheduled: '10 Nov 2026',
      contractor: 'Gandhinagar Police IT Cell',
      firmware: 'v5.9.2',
      uptime_pct: '99.9%',
    },
    history: [
      { date: '2026-09-13 12:15', event: 'State VIP route surveillance check complete', author: 'Command Center' },
      { date: '2026-08-10 11:00', event: '60fps optical tracking test 100% pass', author: 'Tech #01' },
    ],
  },
  {
    id: 16,
    camera_uid: 'CAM-GNR-002',
    name: 'Sachivalaya Gate 4 Command Node',
    department: 'Police',
    district: 'Gandhinagar',
    location: 'Gujarat New State Secretariat Compound',
    type: 'Box Thermal',
    latitude: 23.2156,
    longitude: 72.6369,
    vms_vendor: 'Axis Communications Q1942-E',
    protocol_type: 'HLS',
    status: 'Online',
    installed_on: '15 May 2025',
    power_source: 'Sachivalaya Redundant Sub-station',
    warranty_status: 'Active (Until May 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '4K (3840x2160)',
    created_at: '2026-08-17T08:00:00Z',
    updated_at: '2026-09-13T12:30:00Z',
    maintenance: {
      last_serviced: '15 Aug 2026',
      next_scheduled: '15 Nov 2026',
      contractor: 'State Intelligence Bureau IT',
      firmware: 'v4.12.8',
      uptime_pct: '100.0%',
    },
    history: [
      { date: '2026-09-13 12:30', event: 'Thermal perimeter intrusion scan: Nominal', author: 'Pipeline 3' },
    ],
  },
  {
    id: 17,
    camera_uid: 'CAM-GNR-003',
    name: 'Central University of Gujarat Admin Block',
    department: 'Education',
    district: 'Gandhinagar',
    location: 'Sector 29 Academic Campus',
    type: 'Fisheye 360°',
    latitude: 23.2274,
    longitude: 72.6481,
    vms_vendor: 'CP Plus Intellinet',
    protocol_type: 'ONVIF',
    status: 'Online',
    installed_on: '20 May 2025',
    power_source: 'Campus Green Solar Grid',
    warranty_status: 'Active (Until May 2027)',
    ai_enabled: true,
    fps: 25,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-17T09:00:00Z',
    updated_at: '2026-09-13T10:00:00Z',
    maintenance: {
      last_serviced: '20 Aug 2026',
      next_scheduled: '20 Nov 2026',
      contractor: 'Gujarat Educational Tech',
      firmware: 'v2.9.0',
      uptime_pct: '99.3%',
    },
    history: [
      { date: '2026-09-05 14:15', event: 'Campus entrance de-warping verified', author: 'System' },
    ],
  },
  {
    id: 18,
    camera_uid: 'CAM-GNR-004',
    name: 'Gandhinagar Civil Hospital Oxygen Plant',
    department: 'Health',
    district: 'Gandhinagar',
    location: 'Sector 12 Hospital Medical Infrastructure',
    type: 'Bullet Fixed',
    latitude: 23.2185,
    longitude: 72.6412,
    vms_vendor: 'Hanwha Techwin',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '28 May 2025',
    power_source: 'Hospital Priority Grid',
    warranty_status: 'Active (Until May 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-17T10:00:00Z',
    updated_at: '2026-09-13T11:00:00Z',
    maintenance: {
      last_serviced: '28 Aug 2026',
      next_scheduled: '28 Nov 2026',
      contractor: 'Health Services Gujarat',
      firmware: 'v3.4.2',
      uptime_pct: '99.9%',
    },
    history: [
      { date: '2026-09-12 11:00', event: 'Cryogenic vessel visual perimeter check normal', author: 'System' },
    ],
  },
  {
    id: 19,
    camera_uid: 'CAM-RJK-001',
    name: 'Yagnik Road Commercial Hub',
    department: 'Police',
    district: 'Rajkot',
    location: 'Yagnik Road Crossroad Junction',
    type: 'PTZ Dome',
    latitude: 22.2969,
    longitude: 70.7984,
    vms_vendor: 'CP Plus 4K Pro',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '05 Jun 2025',
    power_source: 'PoE+ (IEEE 802.3at)',
    warranty_status: 'Active (Until Jun 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-16T14:00:00Z',
    updated_at: '2026-09-13T11:00:00Z',
    maintenance: {
      last_serviced: '16 Aug 2026',
      next_scheduled: '16 Nov 2026',
      contractor: 'Rajkot City Eye SPV',
      firmware: 'v3.1.0',
      uptime_pct: '99.5%',
    },
    history: [
      { date: '2026-09-13 11:00', event: 'Commercial street patrol telemetry checked', author: 'System' },
    ],
  },
  {
    id: 20,
    camera_uid: 'CAM-RJK-002',
    name: 'Rajkot Central Bus Station Outbound',
    department: 'Transport',
    district: 'Rajkot',
    location: 'GSRTC Central Terminus Concourse',
    type: 'ANPR High-Speed',
    latitude: 22.3021,
    longitude: 70.8035,
    vms_vendor: 'Dahua WizMind',
    protocol_type: 'ONVIF',
    status: 'Online',
    installed_on: '12 Jun 2025',
    power_source: 'GSRTC Terminal Mains + UPS',
    warranty_status: 'Active (Until Jun 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-16T15:00:00Z',
    updated_at: '2026-09-13T11:30:00Z',
    maintenance: {
      last_serviced: '20 Aug 2026',
      next_scheduled: '20 Nov 2026',
      contractor: 'GSRTC Telematics',
      firmware: 'v2.8.9',
      uptime_pct: '99.7%',
    },
    history: [
      { date: '2026-09-12 09:15', event: 'Bus bay license plate OCR OCR test 99.2%', author: 'Pipeline 4' },
    ],
  },
  {
    id: 21,
    camera_uid: 'CAM-BHV-001',
    name: 'Ghogha Port Marine Terminal Approach',
    department: 'Transport',
    district: 'Bhavnagar',
    location: 'Ro-Ro Ferry Terminal Main Gate',
    type: 'Box Thermal',
    latitude: 21.6881,
    longitude: 72.2798,
    vms_vendor: 'Axis Communications Q1942-E',
    protocol_type: 'RTSP',
    status: 'Online',
    installed_on: '20 Jun 2025',
    power_source: 'Gujarat Maritime Board Grid',
    warranty_status: 'Active (Until Jun 2028)',
    ai_enabled: true,
    fps: 25,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-18T10:00:00Z',
    updated_at: '2026-09-13T09:00:00Z',
    maintenance: {
      last_serviced: '18 Aug 2026',
      next_scheduled: '18 Nov 2026',
      contractor: 'Maritime Coastal Telecom',
      firmware: 'v4.12.2',
      uptime_pct: '99.6%',
    },
    history: [
      { date: '2026-09-13 09:00', event: 'Vessel berthing infrared vision sync pass', author: 'System' },
    ],
  },
  {
    id: 22,
    camera_uid: 'CAM-BHV-002',
    name: 'Bhavnagar Solid Waste Resource Facility',
    department: 'Municipal Corporation',
    district: 'Bhavnagar',
    location: 'BMC Processing Yard Chitra Ward',
    type: 'Bullet Fixed',
    latitude: 21.7645,
    longitude: 72.1519,
    vms_vendor: 'CP Plus 5MP Fixed',
    protocol_type: 'ONVIF',
    status: 'Maintenance',
    installed_on: '28 Jun 2025',
    power_source: 'Municipal Solar Feed',
    warranty_status: 'Active (Until Jun 2027)',
    ai_enabled: true,
    fps: 20,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-18T11:00:00Z',
    updated_at: '2026-09-13T08:30:00Z',
    maintenance: {
      last_serviced: '12 Sep 2026',
      next_scheduled: '15 Sep 2026',
      contractor: 'BMC Engineering Cell',
      firmware: 'v2.1.0',
      uptime_pct: '93.5%',
    },
    history: [
      { date: '2026-09-12 14:00', event: 'Dust filter assembly replacement scheduled', author: 'Tech #33' },
    ],
  },
  {
    id: 23,
    camera_uid: 'CAM-JMN-001',
    name: 'Reliance Greens Highway Checkpoint',
    department: 'Transport',
    district: 'Jamnagar',
    location: 'Motikhavdi NH-947 Petrochem Corridor',
    type: 'ANPR High-Speed',
    latitude: 22.3852,
    longitude: 69.8512,
    vms_vendor: 'Dahua 4K ANPR',
    protocol_type: 'RTSP',
    status: 'Degraded',
    installed_on: '05 Jul 2025',
    power_source: 'Highway Solar Array + Grid',
    warranty_status: 'Active (Until Jul 2028)',
    ai_enabled: true,
    fps: 18,
    resolution: '720p (1280x720)',
    created_at: '2026-08-19T09:30:00Z',
    updated_at: '2026-09-13T08:45:00Z',
    maintenance: {
      last_serviced: '08 Aug 2026',
      next_scheduled: '16 Sep 2026',
      contractor: 'NHAI Highway Electronics',
      firmware: 'v3.5.1',
      uptime_pct: '94.2%',
    },
    history: [
      { date: '2026-09-13 08:45', event: 'Frame jitter detected on cellular backhaul', author: 'Pipeline 2' },
    ],
  },
  {
    id: 24,
    camera_uid: 'CAM-KCH-001',
    name: 'Kandla Port Cargo Entry Terminal 2',
    department: 'Transport',
    district: 'Kutch',
    location: 'Deendayal Port Trust Freight Gate 2',
    type: 'PTZ Dome',
    latitude: 23.0035,
    longitude: 70.2185,
    vms_vendor: 'Axis Communications Q6075-E',
    protocol_type: 'ONVIF',
    status: 'Online',
    installed_on: '15 Jul 2025',
    power_source: 'Port Heavy Duty Industrial Substation',
    warranty_status: 'Active (Until Jul 2028)',
    ai_enabled: true,
    fps: 30,
    resolution: '4K (3840x2160)',
    created_at: '2026-08-20T11:00:00Z',
    updated_at: '2026-09-13T10:20:00Z',
    maintenance: {
      last_serviced: '20 Aug 2026',
      next_scheduled: '20 Nov 2026',
      contractor: 'Deendayal Port Authority',
      firmware: 'v4.12.5',
      uptime_pct: '99.8%',
    },
    history: [
      { date: '2026-09-13 10:20', event: 'Heavy container cargo bay telemetry nominal', author: 'Pipeline 3' },
    ],
  },
  {
    id: 25,
    camera_uid: 'CAM-KCH-002',
    name: 'Bhuj General Hospital Emergency Corridor',
    department: 'Health',
    district: 'Kutch',
    location: 'GK General Hospital GK Campus',
    type: 'Bullet Fixed',
    latitude: 23.2420,
    longitude: 69.6669,
    vms_vendor: 'CP Plus 5MP',
    protocol_type: 'RTSP',
    status: 'Offline',
    installed_on: '22 Jul 2025',
    power_source: 'Hospital Backup UPS',
    warranty_status: 'Active (Until Jul 2027)',
    ai_enabled: true,
    fps: 0,
    resolution: '1080p (1920x1080)',
    created_at: '2026-08-20T12:00:00Z',
    updated_at: '2026-09-13T06:30:00Z',
    maintenance: {
      last_serviced: '10 Jul 2026',
      next_scheduled: '14 Sep 2026 (Priority)',
      contractor: 'Kutch District Health IT',
      firmware: 'v2.2.0',
      uptime_pct: '91.8%',
    },
    history: [
      { date: '2026-09-13 06:30', event: 'Switch port power dropped (PoE fault detected)', author: 'Pipeline 1' },
      { date: '2026-09-13 06:45', event: 'Dispatched maintenance ticket to Kutch Field Ops', author: 'Operations Engine' },
    ],
  },
];

export function getCCTVRegistryStats(cameras = MOCK_CAMERAS) {
  const totalCameras = cameras.length;
  const departments = new Set(cameras.map((c) => c.department).filter(Boolean));
  const locations = new Set(cameras.map((c) => c.location || c.district).filter(Boolean));

  const operationalCount = cameras.filter((c) => {
    const s = (c.status || '').toLowerCase();
    return s === 'online' || s === 'active';
  }).length;

  const offlineCount = cameras.filter((c) => {
    const s = (c.status || '').toLowerCase();
    return s === 'offline' || s === 'inactive';
  }).length;

  const operationalPct = totalCameras > 0 ? ((operationalCount / totalCameras) * 100).toFixed(1) : '0.0';
  const offlinePct = totalCameras > 0 ? ((offlineCount / totalCameras) * 100).toFixed(1) : '0.0';

  return {
    totalCameras,
    totalDepartments: departments.size,
    totalLocations: locations.size,
    operationalCount,
    operationalPct,
    offlineCount,
    offlinePct,
  };
}

export const MOCK_ADAPTERS = [
  {
    protocol: 'RTSP',
    adapter_status: 'HEALTHY',
    active_streams: 1042,
    latency_ms: 142,
    packet_loss_pct: 0.12,
    frame_jitter_ms: 4.2,
    supported_codecs: ['H.264', 'H.265', 'MJPEG'],
  },
  {
    protocol: 'HLS',
    adapter_status: 'HEALTHY',
    active_streams: 248,
    latency_ms: 820,
    packet_loss_pct: 0.04,
    frame_jitter_ms: 1.8,
    supported_codecs: ['H.264', 'AAC'],
  },
  {
    protocol: 'ONVIF',
    adapter_status: 'HEALTHY',
    active_streams: 114,
    latency_ms: 210,
    packet_loss_pct: 0.18,
    frame_jitter_ms: 6.1,
    supported_codecs: ['Profile S', 'Profile T', 'Profile G'],
  },
  {
    protocol: 'VENDOR_SDK',
    adapter_status: 'HEALTHY',
    active_streams: 24,
    latency_ms: 165,
    packet_loss_pct: 0.08,
    frame_jitter_ms: 3.4,
    supported_codecs: ['Hikvision ISAPI', 'Dahua DHOP', 'Axis VAPIX'],
  },
];

export const MOCK_AI_DETECTIONS = [
  {
    detection_id: 'DET-20260913-001',
    camera_uid: 'CAM-AHM-002',
    timestamp: '2026-09-13T11:42:15Z',
    entity_type: 'PERSON',
    label: 'Person of Interest Match',
    confidence: 0.942,
    bbox: { x: 0.32, y: 0.28, width: 0.18, height: 0.44 },
    attributes: {
      gender: 'Male',
      estimated_age: '32-38',
      clothing_upper: 'Dark grey jacket',
      clothing_lower: 'Blue jeans',
      accessories: ['Black backpack', 'Face mask (partial)'],
    },
    risk_score: 88,
  },
  {
    detection_id: 'DET-20260913-002',
    camera_uid: 'CAM-SRT-001',
    timestamp: '2026-09-13T11:43:12Z',
    entity_type: 'VEHICLE',
    label: 'Watchlist Vehicle',
    confidence: 0.987,
    bbox: { x: 0.45, y: 0.35, width: 0.34, height: 0.28 },
    attributes: {
      license_plate: 'GJ05X7821',
      vehicle_make: 'Honda',
      vehicle_model: 'City',
      vehicle_color: 'White',
      speed_kmh: 52,
      heading: 'South-East',
    },
    risk_score: 96,
  },
  {
    detection_id: 'DET-20260913-003',
    camera_uid: 'CAM-KCH-001',
    timestamp: '2026-09-13T11:31:44Z',
    entity_type: 'OBJECT',
    label: 'Unregistered Cargo Transfer',
    confidence: 0.914,
    bbox: { x: 0.22, y: 0.48, width: 0.26, height: 0.32 },
    attributes: {
      object_type: 'Sealed Drum / Tanker Valve',
      anomaly_type: 'Prohibited offloading zone',
      duration_stationary_sec: 720,
      department: 'Food Safety',
    },
    risk_score: 84,
  },
  {
    detection_id: 'DET-20260913-004',
    camera_uid: 'CAM-BHV-001',
    timestamp: '2026-09-13T11:26:08Z',
    entity_type: 'EVENT',
    label: 'Grain Depot Off-Hour Activity',
    confidence: 0.961,
    bbox: { x: 0.15, y: 0.30, width: 0.50, height: 0.40 },
    attributes: {
      anomaly_type: 'Curfew / Off-Hours Depot Breach',
      vehicle_detected: 'Unmarked Commercial Truck',
      pds_stock_risk: 'High',
      department: 'Civil Supplies',
    },
    risk_score: 91,
  },
  {
    detection_id: 'DET-20260913-005',
    camera_uid: 'CAM-VDR-001',
    timestamp: '2026-09-13T11:15:30Z',
    entity_type: 'OBJECT',
    label: 'Unattended Luggage',
    confidence: 0.892,
    bbox: { x: 0.52, y: 0.62, width: 0.12, height: 0.15 },
    attributes: {
      object_type: 'Black Trolley Bag',
      dwell_time_mins: 22,
      perimeter: 'High Footfall Garden Promenade',
      owner_proximity: 'None within 25m',
    },
    risk_score: 79,
  },
];

export const MOCK_INTELLIGENCE_EVENTS = [
  {
    id: 1,
    event_id: 'EVT-20260913-001',
    event_type: 'WATCHLIST_VEHICLE_CORRELATED',
    timestamp: '2026-09-13T11:43:12Z',
    severity: 'CRITICAL',
    confidence: 0.987,
    description: 'Vehicle GJ05X7821 identified across 3 successive highway nodes within 12 minutes.',
    related_entities: ['VEH-GJ05X7821', 'CAM-SRT-001', 'CAM-SRT-002'],
    evidence: {
      plate_crop_url: '/assets/plate_gj05x7821.jpg',
      full_frame_url: '/assets/frame_srt_001.jpg',
      first_seen_camera: 'CAM-SRT-001',
      last_seen_camera: 'CAM-SRT-002',
    },
    status: 'ACTIVE',
  },
  {
    id: 2,
    event_id: 'EVT-20260913-002',
    event_type: 'MISSING_PERSON_CANDIDATE',
    timestamp: '2026-09-13T11:42:15Z',
    severity: 'HIGH',
    confidence: 0.942,
    description: 'Person feature vector strongly correlates with Gujarat CID Missing Advisory #MP-2026-0412.',
    related_entities: ['PER-CID-0412', 'CAM-AHM-002', 'CAM-AHM-001'],
    evidence: {
      face_similarity_score: 0.942,
      advisory_id: 'MP-2026-0412',
      missing_since: '2026-09-11',
    },
    status: 'ACTIVE',
  },
  {
    id: 3,
    event_id: 'EVT-20260913-003',
    event_type: 'FOOD_SAFETY_STOCK_ANOMALY',
    timestamp: '2026-09-13T11:31:44Z',
    severity: 'HIGH',
    confidence: 0.914,
    description: 'Edible oil transfer detected outside authorized gate pass hours at Kandla cargo berth.',
    related_entities: ['OBJ-OIL-DRUM-90', 'CAM-KCH-001'],
    evidence: {
      declared_manifest: 'Industrial Mineral Salt',
      detected_cargo: 'Bulk Edible Oil Drums',
    },
    status: 'ACTIVE',
  },
  {
    id: 4,
    event_id: 'EVT-20260913-004',
    event_type: 'CIVIL_SUPPLIES_DEPOT_BREACH',
    timestamp: '2026-09-13T11:26:08Z',
    severity: 'CRITICAL',
    confidence: 0.961,
    description: 'Unscheduled bulk PDS wheat grain loading at Kalupur / Bhavnagar depot perimeter.',
    related_entities: ['VEH-UNREG-TRK', 'CAM-BHV-001'],
    evidence: {
      expected_gate_status: 'LOCKED',
      detected_activity: 'Forklift pallet relocation',
    },
    status: 'ACTIVE',
  },
  {
    id: 5,
    event_id: 'EVT-20260913-005',
    event_type: 'UNATTENDED_OBJECT_PUBLIC_HAZARD',
    timestamp: '2026-09-13T11:15:30Z',
    severity: 'MEDIUM',
    confidence: 0.892,
    description: 'Stationary trolley bag unattended for over 20 minutes in public pedestrian corridor.',
    related_entities: ['OBJ-BAG-VDR-01', 'CAM-VDR-001'],
    evidence: {
      first_detected: '2026-09-13T10:53:10Z',
      dwell_mins: 22,
    },
    status: 'ACTIVE',
  },
];

export const MOCK_WATCHLIST_MATCHES = [
  {
    id: 1,
    match_id: 'WLM-20260913-001',
    watchlist_id: 'WL-STATE-CRIME-882',
    entity_id: 'VEH-GJ05X7821',
    match_type: 'LICENSE_PLATE_EXACT',
    confidence: 0.987,
    timestamp: '2026-09-13T11:43:12Z',
    watchlist_title: 'Stolen Luxury Sedan Interstate Syndicate',
    issuing_agency: 'Surat Police Crime Branch',
  },
  {
    id: 2,
    match_id: 'WLM-20260913-002',
    watchlist_id: 'WL-CID-MISSING-0412',
    entity_id: 'PER-CID-0412',
    match_type: 'FACIAL_AND_BIOMETRIC_FEATURE',
    confidence: 0.942,
    timestamp: '2026-09-13T11:42:15Z',
    watchlist_title: 'Statewide Missing Minor / Youth Advisory',
    issuing_agency: 'Gujarat State CID Intelligence',
  },
  {
    id: 3,
    match_id: 'WLM-20260913-003',
    watchlist_id: 'WL-FOOD-SAFETY-019',
    entity_id: 'OBJ-OIL-DRUM-90',
    match_type: 'COMMERCIAL_CONTRABAND_SIGNATURE',
    confidence: 0.914,
    timestamp: '2026-09-13T11:31:44Z',
    watchlist_title: 'Adulterated Mustard Oil Diversion Alert',
    issuing_agency: 'Food & Drugs Control Administration Gujarat',
  },
];

export const MOCK_ENTITY_TIMELINES = {
  'VEH-GJ05X7821': [
    {
      observation_id: 'OBS-001',
      entity_id: 'VEH-GJ05X7821',
      camera_uid: 'CAM-SRT-001',
      camera_name: 'Majura Gate Flyover',
      district: 'Surat',
      timestamp: '2026-09-13T11:31:02Z',
      confidence: 0.975,
      speed_kmh: 46,
      heading: 'East',
    },
    {
      observation_id: 'OBS-002',
      entity_id: 'VEH-GJ05X7821',
      camera_uid: 'CAM-SRT-002',
      camera_name: 'Varachha Diamond Market Square',
      district: 'Surat',
      timestamp: '2026-09-13T11:38:40Z',
      confidence: 0.982,
      speed_kmh: 48,
      heading: 'South-East',
    },
    {
      observation_id: 'OBS-003',
      entity_id: 'VEH-GJ05X7821',
      camera_uid: 'CAM-SRT-003',
      camera_name: 'Kamrej Toll Plaza Outer Cord',
      district: 'Surat',
      timestamp: '2026-09-13T11:43:12Z',
      confidence: 0.987,
      speed_kmh: 52,
      heading: 'Highway NH-48 Towards Vadodara',
    },
  ],
  'PER-CID-0412': [
    {
      observation_id: 'OBS-101',
      entity_id: 'PER-CID-0412',
      camera_uid: 'CAM-AHM-002',
      camera_name: 'Kalupur Central Railway Station Gate 1',
      district: 'Ahmedabad',
      timestamp: '2026-09-13T11:22:10Z',
      confidence: 0.918,
      activity: 'Departing Platform 4 Underpass',
    },
    {
      observation_id: 'OBS-102',
      entity_id: 'PER-CID-0412',
      camera_uid: 'CAM-AHM-003',
      camera_name: 'Sarangpur Transit Footover Bridge',
      district: 'Ahmedabad',
      timestamp: '2026-09-13T11:34:55Z',
      confidence: 0.935,
      activity: 'Walking towards BRTS corridor',
    },
    {
      observation_id: 'OBS-103',
      entity_id: 'PER-CID-0412',
      camera_uid: 'CAM-AHM-001',
      camera_name: 'Sabarmati Riverfront North Promenade',
      district: 'Ahmedabad',
      timestamp: '2026-09-13T11:42:15Z',
      confidence: 0.942,
      activity: 'Observed sitting near Promenade Bench #14',
    },
  ],
};

// Shape matches the real backend's AlertResponse (server/schemas/alert.py) exactly --
// type/severity/status enum values, entity/camera_uid/camera_name/district as flat
// strings, confidence as a 0-1 float, created_at/updated_at as ISO timestamps -- not
// the old alert_id/alert_type/subject/title/priority shape this used to have.
//
// Found the hard way: a real Playwright + axe-core accessibility audit crashed
// Analytics.jsx and Investigation.jsx with "Cannot read properties of undefined
// (reading 'replace')" the moment the backend was briefly unreachable (a real CORS
// misconfig hit during that same audit, since fixed in server/core/config.py) and the
// client fell back to this mock data -- every real-schema-shaped component calls
// `.type.replace(...)` on alert objects, and this array's old `alert_type` field left
// `.type` undefined. Mock mode is a real, supported fallback path (Topbar's
// LIVE/MOCK pill), not a rarely-hit corner -- it must render, not crash, whenever the
// backend is genuinely unreachable. Also drops the fake officer_id/officer_location/eta
// fields this array still carried; the real UI stopped reading them when the fabricated
// "nearest patrol officer" panel was removed from Investigation.jsx (docs/prd.md §15).
export const MOCK_OPERATIONAL_ALERTS = [
  {
    id: 1,
    alert_uid: 'ALT-20260913-001',
    severity: 'CRITICAL',
    type: 'WATCHLIST_MATCH',
    description: 'Vehicle matched against State Crime Registry syndicate watchlist. Correlated trajectory shows continuous eastward escape vector.',
    entity: 'GJ05X7821',
    camera_uid: 'CAM-SRT-014',
    camera_name: 'Surat Ring Road / Kamrej Toll',
    district: 'Surat',
    status: 'NEW',
    confidence: 0.987,
    investigation_id: null,
    created_at: '2026-09-13T11:43:12Z',
    updated_at: '2026-09-13T11:43:12Z',
  },
  {
    id: 2,
    alert_uid: 'ALT-20260913-002',
    severity: 'HIGH',
    type: 'PERSON_MATCH',
    description: 'High biometric match confidence at Sabarmati Promenade. Visual confirmation needed by field officer before contact.',
    entity: 'Rohan Sharma (Missing Advisory #0412)',
    camera_uid: 'CAM-AHM-027',
    camera_name: 'Sabarmati Riverfront North',
    district: 'Ahmedabad',
    status: 'ACKNOWLEDGED',
    confidence: 0.942,
    investigation_id: null,
    created_at: '2026-09-13T11:42:15Z',
    updated_at: '2026-09-13T11:42:15Z',
  },
  {
    id: 3,
    alert_uid: 'ALT-20260913-003',
    severity: 'HIGH',
    type: 'ANOMALY',
    description: 'Thermal and visual analysis indicates offloading of unmanifested drums at APMC Market Yard / Port Warehouse.',
    entity: 'Cold Storage Oil Stock Anomaly',
    camera_uid: 'CAM-KCH-009',
    camera_name: 'Kandla Freight Yard Berth 4',
    district: 'Kutch',
    status: 'NEW',
    confidence: 0.914,
    investigation_id: null,
    created_at: '2026-09-13T11:31:44Z',
    updated_at: '2026-09-13T11:31:44Z',
  },
  {
    id: 4,
    alert_uid: 'ALT-20260913-004',
    severity: 'CRITICAL',
    type: 'ANOMALY',
    description: 'Vehicle loading detected during non-operational warehouse curfew hours. Immediate spot verification ordered.',
    entity: 'Ration Depot Off-Hours Inventory Movement',
    camera_uid: 'CAM-BHV-005',
    camera_name: 'Ghogha Port Civil Depot',
    district: 'Bhavnagar',
    status: 'ACKNOWLEDGED',
    confidence: 0.961,
    investigation_id: null,
    created_at: '2026-09-13T11:26:08Z',
    updated_at: '2026-09-13T11:26:08Z',
  },
  {
    id: 5,
    alert_uid: 'ALT-20260913-005',
    severity: 'MEDIUM',
    type: 'ANOMALY',
    description: 'Stationary luggage bag left without owner in high-density recreational zone (22 min dwell time).',
    entity: 'Unattended Luggage',
    camera_uid: 'CAM-VDR-011',
    camera_name: 'Sayaji Baug West Gate',
    district: 'Vadodara',
    status: 'NEW',
    confidence: 0.892,
    investigation_id: null,
    created_at: '2026-09-13T11:15:30Z',
    updated_at: '2026-09-13T11:15:30Z',
  },
];
